/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/  ////////////////////////////////////////////
var skycons = new Skycons();

// you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
skycons.add("day1", Skycons.CLEAR_DAY);
skycons.add("day2", Skycons.CLOUDY);
skycons.add("day3", Skycons.RAIN);

// start all icons animation!
skycons.play();

// update a icon on  canvas by its id
skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);

/*
Get value from Bootstrap dropdown menu
*/

var areas = ["Taipei City","New Taipei City","Taichung City","Tainan City","Kaohsiung City","Keelung City","Taoyuan City","Hsinchu City","Hsinchu County","Miaoli County","Changhua County","Nantou County","Yunlin County","Chiayi City","Chiayi County","Pingtung County","Yilan County","Hualien County","Taitung County","Penghu County","Kinmen County","Matsu"];

//Show Taipei's Weather First
$(document).ready(function() {
    getJsonUntilSuccess("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taipei%20City%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",
        function(data) {
            var currentTemperature = toCelsius(data.query.results.channel.item.condition.temp);
            $('#tempNow').text(currentTemperature);
            updatePage(0);
        })
      }
);

//All Cities temperature in the Dropdown List
var $temps = $('#dropdown li span');
$temps.each(function(index, element) {
    var $temp = $(this);
    getJsonUntilSuccess("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + areas[index] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",   //areas[index] 可以直接跑過所有地點
        function(data) {
            var currentTemperature = toCelsius(data.query.results.channel.item.condition.temp);
            $temp.text(currentTemperature);
        });
  }
)

//選城市
$('#dropdown li').on('click', function() {
    updatePage($(this).find('a').attr('tabindex'));
    //change toggle info
    $('#selectedArea').html($(this).find('a').html());
});

function updatePage(i) {
    getJsonUntilSuccess("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + areas[i] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",  //areas[i] 可以直接跑過所有地點
        function(data) {
            console.log(data);
            $('.temperature').text(toCelsius(data.query.results.channel.item.condition.temp));
            $('.date').text(data.query.results.channel.item.forecast[0].date);
            var description = data.query.results.channel.item.forecast[0].text;
            $('#description').text(description);
            skycons.set("today", setIcon(description));
            $('.forecast').each(function(index, element) {
                var $date = $(element);
                $date.text(data.query.results.channel.item.forecast[index + 1].date);
            })
            $('.range').each(function(index, element) {
                var $range = $(element);
                $range.text(toCelsius(data.query.results.channel.item.forecast[index + 1].high) + " - " + toCelsius(data.query.results.channel.item.forecast[index + 1].low));
            })
            skycons.set("day1", setIcon(data.query.results.channel.item.forecast[1].text));
            skycons.set("day2", setIcon(data.query.results.channel.item.forecast[2].text));
            skycons.set("day3", setIcon(data.query.results.channel.item.forecast[3].text));
        }
      );
}

//華氏轉攝氏 FUNCTION
function toCelsius(fahrenheit) {
    var c = ((5 / 9) * (fahrenheit - 32)).toFixed(1)
    return c;
}
//助教的CODE
function getJsonUntilSuccess(url, callback) {
    $.getJSON(url, function(data) {
        if (data.query.results) { // if data.query.results exist , do the following action.
            callback(data);
        } else {
            getJsonUntilSuccess(url, callback);
        }
    })
}

function setIcon(description) {
    switch (description) {
        case "Sunny":
            return "clear-day";
            break;
        case "Mostly Sunny":
            return "clear-day";
            break;
        case "Partly Cloudy":
            return "partly-cloudy-day";
            break;
        case "Mostly Cloudy":
            return "cloudy";
            break;
        case "Cloudy":
            return "cloudy";
            break;
        case "Windy":
            return "wind";
            break;
        case "Breezy":
            return "wind";
            break;
        case "Fog":
            return "fog";
            break;
        default:
            return "rain";
            break;
    }
}
